name: Continuous integration
on: [pull_request, push]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 11.5
      - run: brew install numworks/tap/epsilon-sdk
      - uses: actions/checkout@v2
      - run: make -j2 PLATFORM=simulator ARCH=x86_64 test.headless.bin
      - run: output/release/simulator/macos/x86_64/test.headless.bin
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-macos.zip
          path: output/release/simulator/macos/epsilon.app
env:
  ACCEPT_OFFICIAL_TOS: 1
